import { User, CouncilRole, Issue, Comment, StatusUpdate, EmailOutboxItem } from '@/types';

export const SEED_USERS: User[] = [
  // Council Members & Admins
  {
    id: 'user-pres',
    roll_no: 'PGP40001',
    name: 'Ashwin Narayan',
    email: 'ashwinsvasv+president@gmail.com',
    course: 'PGP',
    batch: '40',
    hostel: 'Hostel 3',
    is_active: true,
  },
  {
    id: 'user-infra',
    roll_no: 'PGP40012',
    name: 'Kabir Mehta',
    email: 'ashwinsvasv+infra@gmail.com',
    course: 'PGP',
    batch: '40',
    hostel: 'Hostel 3',
    is_active: true,
  },
  {
    id: 'user-mess',
    roll_no: 'PGP40045',
    name: 'Ananya Sen',
    email: 'ashwinsvasv+mess@gmail.com',
    course: 'PGP',
    batch: '40',
    hostel: 'Hostel 4',
    is_active: true,
  },
  {
    id: 'user-acad',
    roll_no: 'PGP40089',
    name: 'Rohan Kulkarni',
    email: 'ashwinsvasv+acad@gmail.com',
    course: 'PGP',
    batch: '40',
    hostel: 'Hostel 1',
    is_active: true,
  },
  {
    id: 'user-sports',
    roll_no: 'PGP40104',
    name: 'Tanvi Verma',
    email: 'ashwinsvasv+sports@gmail.com',
    course: 'PGP',
    batch: '40',
    hostel: 'Hostel 2',
    is_active: true,
  },
  {
    id: 'user-events',
    roll_no: 'PGP40122',
    name: 'Devashish Roy',
    email: 'ashwinsvasv+events@gmail.com',
    course: 'PGP',
    batch: '40',
    hostel: 'Hostel 5',
    is_active: true,
  },
  {
    id: 'user-cultural',
    roll_no: 'PGP40156',
    name: 'Meera Iyer',
    email: 'ashwinsvasv+cultural@gmail.com',
    course: 'PGP',
    batch: '40',
    hostel: 'Hostel 4',
    is_active: true,
  },
  {
    id: 'user-treasurer',
    roll_no: 'PGP40188',
    name: 'Siddharth Jain',
    email: 'ashwinsvasv+treasurer@gmail.com',
    course: 'PGP',
    batch: '40',
    hostel: 'Hostel 3',
    is_active: true,
  },
  // 17 Hostel Representatives (Hostel 1 to Hostel 17)
  { id: 'user-h1rep', roll_no: 'PGP41011', name: 'Rohan Sharma', email: 'ashwinsvasv+h1rep@gmail.com', course: 'PGP', batch: '41', hostel: 'Hostel 1', is_active: true },
  { id: 'user-h2rep', roll_no: 'PGP41022', name: 'Aayush Verma', email: 'ashwinsvasv+h2rep@gmail.com', course: 'PGP', batch: '41', hostel: 'Hostel 2', is_active: true },
  { id: 'user-h3rep', roll_no: 'PGP41030', name: 'Vikramaditya Rao', email: 'ashwinsvasv+h3rep@gmail.com', course: 'PGP', batch: '41', hostel: 'Hostel 3', is_active: true },
  { id: 'user-h4rep', roll_no: 'PGP41075', name: 'Pooja Hegde', email: 'ashwinsvasv+h4rep@gmail.com', course: 'PGP', batch: '41', hostel: 'Hostel 4', is_active: true },
  { id: 'user-h5rep', roll_no: 'PGP41055', name: 'Manish Kothari', email: 'ashwinsvasv+h5rep@gmail.com', course: 'PGP', batch: '41', hostel: 'Hostel 5', is_active: true },
  { id: 'user-h6rep', roll_no: 'PGP41066', name: 'Snehal Patil', email: 'ashwinsvasv+h6rep@gmail.com', course: 'PGP', batch: '41', hostel: 'Hostel 6', is_active: true },
  { id: 'user-h7rep', roll_no: 'PGP41077', name: 'Varun Chawla', email: 'ashwinsvasv+h7rep@gmail.com', course: 'PGP', batch: '41', hostel: 'Hostel 7', is_active: true },
  { id: 'user-h8rep', roll_no: 'PGP41088', name: 'Tarun Bansal', email: 'ashwinsvasv+h8rep@gmail.com', course: 'PGP', batch: '41', hostel: 'Hostel 8', is_active: true },
  { id: 'user-h9rep', roll_no: 'PGP41099', name: 'Isha Ganguly', email: 'ashwinsvasv+h9rep@gmail.com', course: 'PGP', batch: '41', hostel: 'Hostel 9', is_active: true },
  { id: 'user-h10rep', roll_no: 'PGP41100', name: 'Gautam Singhania', email: 'ashwinsvasv+h10rep@gmail.com', course: 'PGP', batch: '41', hostel: 'Hostel 10', is_active: true },
  { id: 'user-h11rep', roll_no: 'PGP41111', name: 'Kavita Pillai', email: 'ashwinsvasv+h11rep@gmail.com', course: 'PGP', batch: '41', hostel: 'Hostel 11', is_active: true },
  { id: 'user-h12rep', roll_no: 'PGP41122', name: 'Naveen Choudhary', email: 'ashwinsvasv+h12rep@gmail.com', course: 'PGP', batch: '41', hostel: 'Hostel 12', is_active: true },
  { id: 'user-h13rep', roll_no: 'PGP41133', name: 'Deepak Aggarwal', email: 'ashwinsvasv+h13rep@gmail.com', course: 'PGP', batch: '41', hostel: 'Hostel 13', is_active: true },
  { id: 'user-h14rep', roll_no: 'PGP41144', name: 'Shreya Mazumdar', email: 'ashwinsvasv+h14rep@gmail.com', course: 'PGP', batch: '41', hostel: 'Hostel 14', is_active: true },
  { id: 'user-h15rep', roll_no: 'PGP41155', name: 'Abhijit Mukherjee', email: 'ashwinsvasv+h15rep@gmail.com', course: 'PGP', batch: '41', hostel: 'Hostel 15', is_active: true },
  { id: 'user-h16rep', roll_no: 'PGP41166', name: 'Divya Sundaram', email: 'ashwinsvasv+h16rep@gmail.com', course: 'PGP', batch: '41', hostel: 'Hostel 16', is_active: true },
  { id: 'user-h17rep', roll_no: 'PGP41177', name: 'Kartik Venkatesh', email: 'ashwinsvasv+h17rep@gmail.com', course: 'PGP', batch: '41', hostel: 'Hostel 17', is_active: true },

  // 9 Class Representatives (Sections A to I)
  { id: 'user-cr-a', roll_no: 'PGP41201', name: 'Aryan Khanna', email: 'ashwinsvasv+cr_sec_a@gmail.com', course: 'PGP', batch: '41', hostel: 'Hostel 1', is_active: true },
  { id: 'user-cr-b', roll_no: 'PGP41202', name: 'Bhavna Saxena', email: 'ashwinsvasv+cr_sec_b@gmail.com', course: 'PGP', batch: '41', hostel: 'Hostel 2', is_active: true },
  { id: 'user-cr-c', roll_no: 'PGP41203', name: 'Chirag Sethi', email: 'ashwinsvasv+cr_sec_c@gmail.com', course: 'PGP', batch: '41', hostel: 'Hostel 3', is_active: true },
  { id: 'user-cr-d', roll_no: 'PGP41204', name: 'Devika Nair', email: 'ashwinsvasv+cr_sec_d@gmail.com', course: 'PGP', batch: '41', hostel: 'Hostel 4', is_active: true },
  { id: 'user-cr-e', roll_no: 'PGP41205', name: 'Eshan Roy', email: 'ashwinsvasv+cr_sec_e@gmail.com', course: 'PGP', batch: '41', hostel: 'Hostel 5', is_active: true },
  { id: 'user-cr-f', roll_no: 'PGP41206', name: 'Farhan Qureshi', email: 'ashwinsvasv+cr_sec_f@gmail.com', course: 'PGP', batch: '41', hostel: 'Hostel 6', is_active: true },
  { id: 'user-cr-g', roll_no: 'PGP41207', name: 'Gayatri Joshi', email: 'ashwinsvasv+cr_sec_g@gmail.com', course: 'PGP', batch: '41', hostel: 'Hostel 7', is_active: true },
  { id: 'user-cr-h', roll_no: 'PGP41208', name: 'Harshvardhan Rao', email: 'ashwinsvasv+cr_sec_h@gmail.com', course: 'PGP', batch: '41', hostel: 'Hostel 8', is_active: true },
  { id: 'user-cr-i', roll_no: 'PGP41209', name: 'Ishita Sen', email: 'ashwinsvasv+cr_sec_i@gmail.com', course: 'PGP', batch: '41', hostel: 'Hostel 9', is_active: true },

  {
    id: 'user-admin',
    roll_no: 'PGP40099',
    name: 'Tech Admin',
    email: 'techadmin@iiml.ac.in',
    course: 'PGP',
    batch: '40',
    hostel: 'Hostel 3',
    is_active: true,
  },
  // 20 General Students across PGP, ABM, IPM, IPMX
  { id: 'user-stu-1', roll_no: 'PGP41001', name: 'Rahul Sharma', email: 'rahul.s@iiml.ac.in', course: 'PGP', batch: '41', hostel: 'Hostel 3', is_active: true },
  { id: 'user-stu-2', roll_no: 'PGP41002', name: 'Priya Nair', email: 'priya.n@iiml.ac.in', course: 'PGP', batch: '41', hostel: 'Hostel 4', is_active: true },
  { id: 'user-stu-3', roll_no: 'PGP41003', name: 'Aakash Singhal', email: 'aakash.s@iiml.ac.in', course: 'PGP', batch: '41', hostel: 'Hostel 3', is_active: true },
  { id: 'user-stu-4', roll_no: 'PGP41004', name: 'Sneha Patel', email: 'sneha.p@iiml.ac.in', course: 'PGP', batch: '41', hostel: 'Hostel 2', is_active: true },
  { id: 'user-stu-5', roll_no: 'PGP41005', name: 'Arjun Das', email: 'arjun.d@iiml.ac.in', course: 'PGP', batch: '41', hostel: 'Hostel 1', is_active: true },
  { id: 'user-stu-6', roll_no: 'PGP41006', name: 'Divya Ranganathan', email: 'divya.r@iiml.ac.in', course: 'PGP', batch: '41', hostel: 'Hostel 6', is_active: true },
  { id: 'user-stu-7', roll_no: 'PGP41007', name: 'Karan Joharilal', email: 'karan.j@iiml.ac.in', course: 'PGP', batch: '41', hostel: 'Hostel 5', is_active: true },
  { id: 'user-stu-8', roll_no: 'PGP41008', name: 'Bhavna Menon', email: 'bhavna.m@iiml.ac.in', course: 'PGP', batch: '41', hostel: 'Hostel 7', is_active: true },
  { id: 'user-stu-9', roll_no: 'PGP41009', name: 'Nikhil Agarwal', email: 'nikhil.a@iiml.ac.in', course: 'PGP', batch: '41', hostel: 'Hostel 8', is_active: true },
  { id: 'user-stu-10', roll_no: 'PGP41010', name: 'Shreya Ghosh', email: 'shreya.g@iiml.ac.in', course: 'PGP', batch: '41', hostel: 'Hostel 9', is_active: true },
  { id: 'user-stu-11', roll_no: 'ABM20001', name: 'Abhishek Pandey', email: 'abhishek.p@iiml.ac.in', course: 'ABM', batch: '20', hostel: 'Hostel 10', is_active: true },
  { id: 'user-stu-12', roll_no: 'ABM20002', name: 'Ritika Srivastava', email: 'ritika.s@iiml.ac.in', course: 'ABM', batch: '20', hostel: 'Hostel 11', is_active: true },
  { id: 'user-stu-13', roll_no: 'ABM20003', name: 'Manish Tiwari', email: 'manish.t@iiml.ac.in', course: 'ABM', batch: '20', hostel: 'Hostel 12', is_active: true },
  { id: 'user-stu-14', roll_no: 'ABM20004', name: 'Pallavi Rao', email: 'pallavi.r@iiml.ac.in', course: 'ABM', batch: '20', hostel: 'Hostel 13', is_active: true },
  { id: 'user-stu-15', roll_no: 'IPM04001', name: 'Aditya Mathur', email: 'aditya.m@iiml.ac.in', course: 'IPM', batch: '04', hostel: 'Hostel 14', is_active: true },
  { id: 'user-stu-16', roll_no: 'IPM04002', name: 'Natasha George', email: 'natasha.g@iiml.ac.in', course: 'IPM', batch: '04', hostel: 'Hostel 15', is_active: true },
  { id: 'user-stu-17', roll_no: 'IPM04003', name: 'Kunal Kapoor', email: 'kunal.k@iiml.ac.in', course: 'IPM', batch: '04', hostel: 'Hostel 16', is_active: true },
  { id: 'user-stu-18', roll_no: 'IPM04004', name: 'Anushka Sharma', email: 'anushka.s@iiml.ac.in', course: 'IPM', batch: '04', hostel: 'Hostel 17', is_active: true },
  { id: 'user-stu-19', roll_no: 'PGP40050', name: 'Gaurav Bisht', email: 'gaurav.b@iiml.ac.in', course: 'PGP', batch: '40', hostel: 'Hostel 3', is_active: true },
  { id: 'user-stu-20', roll_no: 'PGP40051', name: 'Harshita Seth', email: 'harshita.s@iiml.ac.in', course: 'PGP', batch: '40', hostel: 'Hostel 4', is_active: true },
];

export const SEED_ROLES: CouncilRole[] = [
  // Executive Student Council
  {
    id: 'role-president',
    name: 'President',
    inbox_email: 'ashwinsvasv+president@gmail.com',
    holder_user_id: 'user-pres',
  },
  {
    id: 'role-infra',
    name: 'Infra & IT Secretary',
    category_domain: 'Infra & IT',
    inbox_email: 'ashwinsvasv+infra@gmail.com',
    holder_user_id: 'user-infra',
  },
  {
    id: 'role-mess',
    name: 'Mess Secretary',
    category_domain: 'Mess and food',
    inbox_email: 'ashwinsvasv+mess@gmail.com',
    holder_user_id: 'user-mess',
  },
  {
    id: 'role-acad',
    name: 'Academic Secretary',
    category_domain: 'Academics',
    inbox_email: 'ashwinsvasv+acad@gmail.com',
    holder_user_id: 'user-acad',
  },
  {
    id: 'role-sports',
    name: 'Sports Secretary',
    category_domain: 'Sports facilities and events',
    inbox_email: 'ashwinsvasv+sports@gmail.com',
    holder_user_id: 'user-sports',
  },
  {
    id: 'role-events',
    name: 'Events Secretary',
    category_domain: 'Events',
    inbox_email: 'ashwinsvasv+events@gmail.com',
    holder_user_id: 'user-events',
  },
  {
    id: 'role-cultural',
    name: 'Cultural Secretary',
    category_domain: 'Cultural',
    inbox_email: 'ashwinsvasv+cultural@gmail.com',
    holder_user_id: 'user-cultural',
  },
  {
    id: 'role-treasurer',
    name: 'Treasurer',
    category_domain: 'Finance and reimbursements',
    inbox_email: 'ashwinsvasv+treasurer@gmail.com',
    holder_user_id: 'user-treasurer',
  },
  {
    id: 'role-student-affairs',
    name: 'Student Affairs Office',
    inbox_email: 'ashwinsvasv+studentaffairs@gmail.com',
    holder_user_id: 'user-admin',
  },

  // 17 Hostel Representatives
  { id: 'role-h1rep', name: 'Hostel Rep H1', inbox_email: 'ashwinsvasv+h1rep@gmail.com', holder_user_id: 'user-h1rep' },
  { id: 'role-h2rep', name: 'Hostel Rep H2', inbox_email: 'ashwinsvasv+h2rep@gmail.com', holder_user_id: 'user-h2rep' },
  { id: 'role-h3rep', name: 'Hostel Rep H3', inbox_email: 'ashwinsvasv+h3rep@gmail.com', holder_user_id: 'user-h3rep' },
  { id: 'role-h4rep', name: 'Hostel Rep H4', inbox_email: 'ashwinsvasv+h4rep@gmail.com', holder_user_id: 'user-h4rep' },
  { id: 'role-h5rep', name: 'Hostel Rep H5', inbox_email: 'ashwinsvasv+h5rep@gmail.com', holder_user_id: 'user-h5rep' },
  { id: 'role-h6rep', name: 'Hostel Rep H6', inbox_email: 'ashwinsvasv+h6rep@gmail.com', holder_user_id: 'user-h6rep' },
  { id: 'role-h7rep', name: 'Hostel Rep H7', inbox_email: 'ashwinsvasv+h7rep@gmail.com', holder_user_id: 'user-h7rep' },
  { id: 'role-h8rep', name: 'Hostel Rep H8', inbox_email: 'ashwinsvasv+h8rep@gmail.com', holder_user_id: 'user-h8rep' },
  { id: 'role-h9rep', name: 'Hostel Rep H9', inbox_email: 'ashwinsvasv+h9rep@gmail.com', holder_user_id: 'user-h9rep' },
  { id: 'role-h10rep', name: 'Hostel Rep H10', inbox_email: 'ashwinsvasv+h10rep@gmail.com', holder_user_id: 'user-h10rep' },
  { id: 'role-h11rep', name: 'Hostel Rep H11', inbox_email: 'ashwinsvasv+h11rep@gmail.com', holder_user_id: 'user-h11rep' },
  { id: 'role-h12rep', name: 'Hostel Rep H12', inbox_email: 'ashwinsvasv+h12rep@gmail.com', holder_user_id: 'user-h12rep' },
  { id: 'role-h13rep', name: 'Hostel Rep H13', inbox_email: 'ashwinsvasv+h13rep@gmail.com', holder_user_id: 'user-h13rep' },
  { id: 'role-h14rep', name: 'Hostel Rep H14', inbox_email: 'ashwinsvasv+h14rep@gmail.com', holder_user_id: 'user-h14rep' },
  { id: 'role-h15rep', name: 'Hostel Rep H15', inbox_email: 'ashwinsvasv+h15rep@gmail.com', holder_user_id: 'user-h15rep' },
  { id: 'role-h16rep', name: 'Hostel Rep H16', inbox_email: 'ashwinsvasv+h16rep@gmail.com', holder_user_id: 'user-h16rep' },
  { id: 'role-h17rep', name: 'Hostel Rep H17', inbox_email: 'ashwinsvasv+h17rep@gmail.com', holder_user_id: 'user-h17rep' },

  // 9 Class Representatives (Sections A to I)
  { id: 'role-cr-a', name: 'Class Rep Section A', inbox_email: 'ashwinsvasv+cr_sec_a@gmail.com', holder_user_id: 'user-cr-a' },
  { id: 'role-cr-b', name: 'Class Rep Section B', inbox_email: 'ashwinsvasv+cr_sec_b@gmail.com', holder_user_id: 'user-cr-b' },
  { id: 'role-cr-c', name: 'Class Rep Section C', inbox_email: 'ashwinsvasv+cr_sec_c@gmail.com', holder_user_id: 'user-cr-c' },
  { id: 'role-cr-d', name: 'Class Rep Section D', inbox_email: 'ashwinsvasv+cr_sec_d@gmail.com', holder_user_id: 'user-cr-d' },
  { id: 'role-cr-e', name: 'Class Rep Section E', inbox_email: 'ashwinsvasv+cr_sec_e@gmail.com', holder_user_id: 'user-cr-e' },
  { id: 'role-cr-f', name: 'Class Rep Section F', inbox_email: 'ashwinsvasv+cr_sec_f@gmail.com', holder_user_id: 'user-cr-f' },
  { id: 'role-cr-g', name: 'Class Rep Section G', inbox_email: 'ashwinsvasv+cr_sec_g@gmail.com', holder_user_id: 'user-cr-g' },
  { id: 'role-cr-h', name: 'Class Rep Section H', inbox_email: 'ashwinsvasv+cr_sec_h@gmail.com', holder_user_id: 'user-cr-h' },
  { id: 'role-cr-i', name: 'Class Rep Section I', inbox_email: 'ashwinsvasv+cr_sec_i@gmail.com', holder_user_id: 'user-cr-i' },
];

const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600 * 1000).toISOString();
const hoursAhead = (h: number) => new Date(now.getTime() + h * 3600 * 1000).toISOString();
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400 * 1000).toISOString();

export const SEED_ISSUES: Issue[] = [
  // 1. The Hot Water issue - core exit test
  {
    id: 'issue-hot-water',
    raised_by: 'user-stu-1',
    title: 'Geysers non-functional in Hostel 3 2nd floor washrooms',
    details: 'Multiple geysers across the north and east wing bathrooms of Hostel 3 second floor have stopped heating water. With winter approaching, students are forced to shower with ice-cold water or crowd into the 1st floor common washrooms. This issue was raised verbally two weeks ago without resolution.',
    category: 'Infra & IT',
    scope: 'my hostel',
    hostel: 'Hostel 3',
    visibility: 'public',
    status: 'Raised',
    severity: 'High',
    owner_role_id: 'role-h3rep',
    cc_role_ids: ['role-infra'],
    ack_deadline: hoursAhead(24),
    vote_count: 214,
    redirect_count: 0,
    is_priority: true,
    photos: [
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80',
    ],
    created_at: hoursAgo(24),
    updated_at: hoursAgo(24),
  },
  // 2. Wi-Fi Access Point Issue
  {
    id: 'issue-wifi-bodhi',
    raised_by: 'user-stu-3',
    title: 'Wi-Fi APs dropping connections in Bodhi Tree block study rooms',
    details: 'During evening group project hours (9 PM to 2 AM), the Wi-Fi APs in Bodhi Tree study rooms constantly reset IP leases. Over 40 students preparing consulting case competitions cannot access library databases.',
    category: 'Infra & IT',
    scope: 'whole campus',
    hostel: 'Hostel 3',
    visibility: 'public',
    status: 'Acknowledged',
    severity: 'High',
    owner_role_id: 'role-infra',
    ack_deadline: hoursAgo(10),
    next_update_due: hoursAhead(120),
    vote_count: 142,
    redirect_count: 0,
    is_priority: false,
    photos: [],
    created_at: daysAgo(2),
    updated_at: hoursAgo(30),
  },
  // 3. Mess hygiene issue
  {
    id: 'issue-mess-hygiene',
    raised_by: 'user-stu-2',
    title: 'Night canteen hygiene & delayed food preparation in Mess 2',
    details: 'Several food trays are being kept uncovered near the dish collection area. Food order times at the night mess counter have exceeded 45 minutes, with raw salad ingredients left in open containers.',
    category: 'Mess and food',
    scope: 'whole campus',
    hostel: 'Hostel 4',
    visibility: 'public',
    status: 'Raised',
    severity: 'Normal',
    owner_role_id: 'role-mess',
    ack_deadline: hoursAhead(36),
    vote_count: 88,
    redirect_count: 0,
    is_priority: false,
    photos: [
      'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=600&q=80'
    ],
    created_at: hoursAgo(12),
    updated_at: hoursAgo(12),
  },
  // 4. Academic schedule clash
  {
    id: 'issue-acad-clash',
    raised_by: 'user-stu-11',
    title: 'Clash between Corporate Finance midterm exam and placement mock interviews',
    details: 'On Thursday Oct 15, the PGP Corporate Finance makeup test is scheduled at 4 PM, directly overlapping with the mandatory consulting mock interviews arranged by the Placement Committee.',
    category: 'Academics',
    scope: 'whole campus',
    hostel: 'Hostel 1',
    visibility: 'public',
    status: 'In Progress',
    severity: 'Critical',
    owner_role_id: 'role-acad',
    ack_deadline: daysAgo(3),
    next_update_due: hoursAhead(48),
    vote_count: 115,
    redirect_count: 0,
    is_priority: false,
    photos: [],
    created_at: daysAgo(4),
    updated_at: daysAgo(2),
  },
  // 5. Badminton court net & lighting (Completed)
  {
    id: 'issue-sports-court',
    raised_by: 'user-stu-9',
    title: 'Broken badminton court net & poor floodlighting at Sports Complex Court 2',
    details: 'The central badminton net cord snapped and two overhead halogen lights are flickering, creating severe glare during evening matches.',
    category: 'Sports facilities and events',
    scope: 'whole campus',
    hostel: 'Hostel 3',
    visibility: 'public',
    status: 'Completed',
    severity: 'Normal',
    owner_role_id: 'role-sports',
    ack_deadline: daysAgo(6),
    vote_count: 45,
    redirect_count: 0,
    is_priority: false,
    photos: [
      'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=600&q=80'
    ],
    created_at: daysAgo(7),
    updated_at: daysAgo(1),
  },
  // 6. Night shuttle frequency
  {
    id: 'issue-shuttle-bus',
    raised_by: 'user-stu-6',
    title: 'Night bus shuttle frequency during exam preparation week',
    details: 'During midterm weeks, the library stays open until 4 AM but the campus electric buggies stop running at 1 AM. Requesting extension of shuttle service till 3:30 AM.',
    category: 'Other / not sure',
    scope: 'whole campus',
    hostel: 'Hostel 4',
    visibility: 'public',
    status: 'Acknowledged',
    severity: 'Normal',
    owner_role_id: 'role-president',
    ack_deadline: daysAgo(1),
    vote_count: 72,
    redirect_count: 0,
    is_priority: false,
    photos: [],
    created_at: daysAgo(3),
    updated_at: daysAgo(2),
  },
  // 7. Manfest-Varchasva Reimbursements
  {
    id: 'issue-treasurer-reimburse',
    raised_by: 'user-stu-7',
    title: 'Delay in reimbursement for Manfest-Varchasva logistics committee expenses',
    details: 'Bills totaling Rs. 42,000 submitted on Sept 18 have not yet been approved or disbursed. Students paid out of pocket for printer cartridges and stage lighting cords.',
    category: 'Finance and reimbursements',
    scope: 'whole campus',
    hostel: 'Hostel 5',
    visibility: 'private',
    status: 'In Progress',
    severity: 'Normal',
    owner_role_id: 'role-treasurer',
    ack_deadline: daysAgo(5),
    next_update_due: hoursAhead(72),
    vote_count: 1,
    redirect_count: 0,
    is_priority: false,
    photos: [],
    created_at: daysAgo(5),
    updated_at: daysAgo(2),
  },
  // 8. Water cooler in H4
  {
    id: 'issue-h4-water-cooler',
    raised_by: 'user-stu-2',
    title: 'Water dispenser filters not replaced in Hostel 4 ground floor',
    details: 'The TDS level measured on the ground floor dispenser shows 380 PPM, and the red replacement indicator LED is blinking. Needs filter replacement.',
    category: 'Infra & IT',
    scope: 'my hostel',
    hostel: 'Hostel 4',
    visibility: 'public',
    status: 'Raised',
    severity: 'Normal',
    owner_role_id: 'role-h4rep',
    cc_role_ids: ['role-infra'],
    ack_deadline: hoursAhead(30),
    vote_count: 54,
    redirect_count: 0,
    is_priority: false,
    photos: [],
    created_at: hoursAgo(18),
    updated_at: hoursAgo(18),
  },
  // 9. Overdue acknowledgment - Escalated L1 for demoing escalations!
  {
    id: 'issue-chintan-mic',
    raised_by: 'user-stu-5',
    title: 'Sound system microphone feedback and AV sync issue in Chintan Auditorium',
    details: 'During the leadership talk series, lapel mic 3 had high-frequency squeal whenever speakers stood near the podium screen.',
    category: 'Events',
    scope: 'whole campus',
    hostel: 'Hostel 1',
    visibility: 'public',
    status: 'Escalated L1',
    severity: 'High',
    owner_role_id: 'role-events',
    ack_deadline: hoursAgo(8), // Overdue by 8 hours
    vote_count: 19,
    redirect_count: 0,
    is_priority: false,
    photos: [],
    created_at: hoursAgo(56),
    updated_at: hoursAgo(8),
  },
  // 10. Washroom mirror in H3 (Completed)
  {
    id: 'issue-h3-washroom-mirror',
    raised_by: 'user-stu-13',
    title: 'Broken mirror and drainage blockage in Hostel 3 washroom Block A',
    details: 'The washbasin drain was clogging after handwashing and the cracked mirror presented a safety hazard.',
    category: 'Hostel life',
    scope: 'my hostel',
    hostel: 'Hostel 3',
    visibility: 'public',
    status: 'Completed',
    severity: 'Normal',
    owner_role_id: 'role-h3rep',
    cc_role_ids: ['role-infra'],
    ack_deadline: daysAgo(5),
    vote_count: 62,
    redirect_count: 0,
    is_priority: false,
    photos: [],
    created_at: daysAgo(6),
    updated_at: daysAgo(1),
  },
];

export const SEED_STATUS_UPDATES: StatusUpdate[] = [
  {
    id: 'upd-1',
    issue_id: 'issue-hot-water',
    actor_id: 'user-stu-1',
    from_status: 'Raised',
    to_status: 'Raised',
    note: 'Issue submitted and routed to Hostel Rep H3 with Infra & IT Secretary copied.',
    created_at: hoursAgo(24),
  },
  {
    id: 'upd-2',
    issue_id: 'issue-wifi-bodhi',
    actor_id: 'user-stu-3',
    from_status: 'Raised',
    to_status: 'Raised',
    note: 'Issue submitted.',
    created_at: daysAgo(2),
  },
  {
    id: 'upd-3',
    issue_id: 'issue-wifi-bodhi',
    actor_id: 'user-infra',
    from_status: 'Raised',
    to_status: 'Acknowledged',
    note: 'Acknowledged. Contacted Campus IT Computer Centre network team. Log tickets filed.',
    created_at: hoursAgo(30),
  },
  {
    id: 'upd-4',
    issue_id: 'issue-acad-clash',
    actor_id: 'user-acad',
    from_status: 'Acknowledged',
    to_status: 'In Progress',
    note: 'Meeting convened with the PGP Office and Placement Chairperson. Drafting rescheduled slot options.',
    created_at: daysAgo(2),
  },
  {
    id: 'upd-5',
    issue_id: 'issue-sports-court',
    actor_id: 'user-sports',
    from_status: 'In Progress',
    to_status: 'Completed',
    note: 'Replaced torn Yonex court net with new tournament-grade net, and replaced two 400W metal-halide bulbs with new LEDs.',
    photo_url: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=600&q=80',
    created_at: daysAgo(1),
  },
  {
    id: 'upd-6',
    issue_id: 'issue-chintan-mic',
    actor_id: 'user-admin',
    from_status: 'Raised',
    to_status: 'Escalated L1',
    note: 'System auto-escalation: 48-hour acknowledgment deadline passed without response. Escalated to President.',
    created_at: hoursAgo(8),
  },
  {
    id: 'upd-7',
    issue_id: 'issue-h3-washroom-mirror',
    actor_id: 'user-h3rep',
    from_status: 'In Progress',
    to_status: 'Completed',
    note: 'Estate office plumber cleared drain blockage and installed a new framed mirror.',
    created_at: daysAgo(1),
  },
];

export const SEED_COMMENTS: Comment[] = [
  {
    id: 'comm-1',
    issue_id: 'issue-hot-water',
    author_id: 'user-stu-3',
    body: 'Can confirm, 2nd floor bathrooms are freezing. Please expedite before weather gets even colder!',
    removed_by_admin: false,
    created_at: hoursAgo(20),
  },
  {
    id: 'comm-2',
    issue_id: 'issue-hot-water',
    author_id: 'user-stu-9',
    body: 'East wing geyser tripped the circuit breaker 3 times yesterday.',
    removed_by_admin: false,
    created_at: hoursAgo(18),
  },
  {
    id: 'comm-3',
    issue_id: 'issue-hot-water',
    author_id: 'user-h3rep',
    body: 'I have inspected the geysers this morning. The heating elements in 3 geysers need replacement and one thermostat is faulty. Discussing with Estate office.',
    removed_by_admin: false,
    created_at: hoursAgo(15),
  },
  {
    id: 'comm-4',
    issue_id: 'issue-wifi-bodhi',
    author_id: 'user-infra',
    body: 'IT team will run an AP diagnostic survey today between 2 PM and 4 PM.',
    removed_by_admin: false,
    created_at: hoursAgo(24),
  },
];

export const SEED_OUTBOX: EmailOutboxItem[] = [
  {
    id: 'mail-1',
    recipient: 'ashwinsvasv+h3rep@gmail.com',
    template: 'issue_raised',
    subject: '[Sunwai] New Issue Raised: Geysers non-functional in Hostel 3 2nd floor washrooms',
    body: 'A new issue has been raised and assigned to you as Hostel Rep H3. Please acknowledge within 48 hours.\n\nTitle: Geysers non-functional in Hostel 3 2nd floor washrooms\nScope: my hostel\nDeadline: 48 hours',
    issue_id: 'issue-hot-water',
    status: 'sent',
    attempts: 1,
    sent_at: hoursAgo(24),
    created_at: hoursAgo(24),
  },
  {
    id: 'mail-2',
    recipient: 'ashwinsvasv+infra@gmail.com',
    template: 'issue_raised_cc',
    subject: '[Sunwai CC] New Issue in H3: Geysers non-functional in Hostel 3 2nd floor washrooms',
    body: 'You are copied on an infrastructure issue raised for Hostel 3.',
    issue_id: 'issue-hot-water',
    status: 'sent',
    attempts: 1,
    sent_at: hoursAgo(24),
    created_at: hoursAgo(24),
  },
  {
    id: 'mail-3',
    recipient: 'ashwinsvasv+president@gmail.com',
    template: 'escalation_l1',
    subject: '[Sunwai Escalation L1] Unacknowledged Issue: Sound system microphone feedback in Chintan',
    body: 'Issue "Sound system microphone feedback in Chintan Auditorium" was not acknowledged within 48 hours by Events Secretary. It has been escalated to you for action.',
    issue_id: 'issue-chintan-mic',
    status: 'sent',
    attempts: 1,
    sent_at: hoursAgo(8),
    created_at: hoursAgo(8),
  },
  {
    id: 'mail-4',
    recipient: 'ashwinsvasv+mess@gmail.com',
    template: 'ack_deadline_reminder_24h',
    subject: '[Sunwai Urgent Reminder] 24 Hours Left to Acknowledge: Night canteen hygiene',
    body: '24-hour reminder to acknowledge issue. If unacknowledged in 24 hours, it will escalate to Level 1.',
    issue_id: 'issue-mess-hygiene',
    status: 'failed',
    attempts: 1,
    error_message: 'SMTP Connection Gateway Timeout (simulated)',
    created_at: hoursAgo(2),
  }
];

export const SEED_AUDIT_LOG = [
  {
    id: 'audit-1',
    actor_id: 'user-admin',
    actor_name: 'Tech Admin',
    action: 'USER_BULK_IMPORT',
    target: 'users',
    details: 'Initial cohort enrollment: 30 test students across PGP, ABM, and IPM registered.',
    created_at: daysAgo(7),
  },
  {
    id: 'audit-2',
    actor_id: 'user-admin',
    actor_name: 'Tech Admin',
    action: 'ROLE_ASSIGNMENT',
    target: 'roles/role-president',
    details: 'Ashwin Narayan (PGP40001) designated as Student Council President.',
    created_at: daysAgo(7),
  },
  {
    id: 'audit-3',
    actor_id: 'user-admin',
    actor_name: 'Tech Admin',
    action: 'ROLE_ASSIGNMENT',
    target: 'roles/role-h3rep',
    details: 'Vikramaditya Rao (PGP41030) appointed as Hostel Representative for Hostel 3.',
    created_at: daysAgo(5),
  },
  {
    id: 'audit-4',
    actor_id: 'user-admin',
    actor_name: 'Tech Admin',
    action: 'COMMENT_REMOVED',
    target: 'comments/comm-99',
    details: 'Removed derogatory comment targeting mess contractor. Reason: Uncivil language.',
    created_at: daysAgo(2),
  },
];

